CREATE TABLE "flashcards_account" (
	"id" text PRIMARY KEY NOT NULL,
	"accountId" text NOT NULL,
	"providerId" text NOT NULL,
	"userId" text NOT NULL,
	"accessToken" text,
	"refreshToken" text,
	"idToken" text,
	"accessTokenExpiresAt" timestamp,
	"refreshTokenExpiresAt" timestamp,
	"scope" text,
	"password" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "flashcards_cardReview" (
	"id" text PRIMARY KEY NOT NULL,
	"cardId" text NOT NULL,
	"userId" text NOT NULL,
	"difficulty" integer NOT NULL,
	"reviewedAt" timestamp DEFAULT now() NOT NULL,
	"nextReviewAt" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "flashcards_card" (
	"id" text PRIMARY KEY NOT NULL,
	"front" text NOT NULL,
	"back" text NOT NULL,
	"deckId" text NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "flashcards_deck" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"userId" text NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "flashcards_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "flashcards_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	"userId" text
);
--> statement-breakpoint
CREATE TABLE "flashcards_session" (
	"id" text PRIMARY KEY NOT NULL,
	"expiresAt" timestamp NOT NULL,
	"token" text NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"ipAddress" text,
	"userAgent" text,
	"userId" text NOT NULL,
	CONSTRAINT "flashcards_session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "flashcards_user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"emailVerified" boolean DEFAULT false NOT NULL,
	"image" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "flashcards_user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "flashcards_verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expiresAt" timestamp NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "flashcards_account" ADD CONSTRAINT "flashcards_account_userId_flashcards_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."flashcards_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "flashcards_cardReview" ADD CONSTRAINT "flashcards_cardReview_cardId_flashcards_card_id_fk" FOREIGN KEY ("cardId") REFERENCES "public"."flashcards_card"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "flashcards_cardReview" ADD CONSTRAINT "flashcards_cardReview_userId_flashcards_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."flashcards_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "flashcards_card" ADD CONSTRAINT "flashcards_card_deckId_flashcards_deck_id_fk" FOREIGN KEY ("deckId") REFERENCES "public"."flashcards_deck"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "flashcards_deck" ADD CONSTRAINT "flashcards_deck_userId_flashcards_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."flashcards_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "flashcards_post" ADD CONSTRAINT "flashcards_post_userId_flashcards_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."flashcards_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "flashcards_session" ADD CONSTRAINT "flashcards_session_userId_flashcards_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."flashcards_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "name_idx" ON "flashcards_post" USING btree ("name");